apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-demo
    targetRevision: 0.40.6
    helm:
      values: |
        grafana:
          enabled: false
        prometheus:
          enabled: false
        opensearch:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true